import './reset.css';
import './globals.scss';
import type { Metadata } from 'next';
import LayoutClient from './layout.client';
import { getLocalUser } from '@/lib/users/actions';

export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const localUser = await getLocalUser();

    return (
        <html lang="en">
            <LayoutClient localUser={localUser}>
                <body>{children}</body>
            </LayoutClient>
        </html>
    );
}
